# Introduction to Pytorch 

In [3]:
import torch 
import numpy as np 

In [6]:
data = [[2,3],[2,1]]
data_tensor = torch.tensor(data)
print(type(data_tensor))

<class 'torch.Tensor'>


In [8]:
data = [[2,3],[2,1]]
numpy_data = np.array(data)
data_tensor = torch.from_numpy(numpy_data)
print(type(data_tensor))

<class 'torch.Tensor'>


In [30]:
data_tensor

tensor([[2, 3],
        [2, 1]])

In [29]:
data_tensor[:,1]

tensor([3, 1])

In [10]:
torch.ones(5,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [11]:
torch.zeros(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [22]:
# generates random number between 0 and 1 
torch.rand(2,2,3)

tensor([[[0.1391, 0.9927, 0.6436],
         [0.0504, 0.0793, 0.8633]],

        [[0.9317, 0.6285, 0.6684],
         [0.0293, 0.1901, 0.1899]]])

In [27]:
data(2,2)

TypeError: 'list' object is not callable